'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Discord_Chat_Bot_Open_Source_VB.NET.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to main-backcolor: Control
        '''main-forecolor: Black
        '''menu-backcolor: Control
        '''menu-forecolor: Black
        '''channel-tab-backcolor-unselected: ControlLight
        '''channel-tab-backcolor-selected: ControlDarkDark
        '''channel-tab-forecolor-unselected: Black
        '''channel-tab-forecolor-selected: White
        '''channel-bar-backcolor: Black
        '''chat-username-html: pink
        '''chat-channel-html: lime
        '''chat-brackets-html: grey
        '''chat-message-html: white
        '''chat-time-html: orange
        '''chat-background-html: Black
        '''chat-bold: false
        '''chat-italics: false
        '''chat-underline [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property default_theme() As String
            Get
                Return ResourceManager.GetString("default_theme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Streamers: jeremy_youtube,timokles,endeavorgaming,slevanas,criscowild,neoslash72,oomoomanoo,speedruntrainer
        '''stream-announce-live: %username% is now LIVE - %URL%%NL%%TITLE%
        '''stream-announce-offline: %username% is no longer streaming.
        '''admin: ZeroRBDash15,agentsix1
        '''user: Timokles,speedruntrainer,Slevanas,CriscoWild,NeoSlash72,A51 Trooper,Dazja,redtrainer57,Ryuknote322
        '''autoscroll: false
        '''trigger: !
        '''auto-scroll-default: true
        '''auto-connect: false
        '''connected-server: Perfect Dark XBLA
        '''stream-announce-channel: [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property settings() As String
            Get
                Return ResourceManager.GetString("settings", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
